language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-asyncudp
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-webserver
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wifiscan
  - PLATFORMIO_PROJECT_DIR=examples/simba-blink
  - PLATFORMIO_PROJECT_DIR=examples/nonOS-blink
  # - PLATFORMIO_PROJECT_DIR=examples/freeRTOS-blink

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
